import assert from 'node:assert/strict';
import test from 'node:test';
import { reviewMockTurn } from './mockCouncil';
import { buildPetSnapshots } from './pets/petPack';
import { SAMPLE_COUNCIL_TURN } from './sampleTurn';
import type { CodexRuntimeStatus } from './runtime/types';
import { renderCouncilHtml } from './webview';

const council={phase:'ready' as const,provider:'codex' as const,message:'Structured review complete.',turnId:'demo'};
const runtime:CodexRuntimeStatus={phase:'ready',binary:'codex',message:'Connected.',models:[{id:'gpt-5.5',model:'gpt-5.5',displayName:'GPT-5.5',isDefault:true,supportedReasoningEfforts:['medium','high'],defaultReasoningEffort:'medium'}],modelSelection:{model:'gpt-5.5',effort:'medium'},thread:{phase:'ready',message:'Thread ready.',thread:{id:'thread-1'}},turn:{phase:'completed',message:'Done.'}};

test('renders living companions and inject-to-Codex actions',()=>{const review=reviewMockTurn(SAMPLE_COUNCIL_TURN);const html=renderCouncilHtml(SAMPLE_COUNCIL_TURN,review,council,runtime,buildPetSnapshots(review,council,runtime),'system','nonce');assert.match(html,/Living Council/);assert.match(html,/Use in Codex/);assert.match(html,/Save to graph/);assert.match(html,/Greffier/);assert.doesNotMatch(html,/Prepared Council prompt/);});
test('renders graph projection and motion preference',()=>{const turn={...SAMPLE_COUNCIL_TURN,projectContext:{summary:'Decision A',sources:['docs/roadmap.md'],graphNodeCount:3,graphEdgeCount:4,storagePath:'.pets-council/shared-context-graph.json'}};const review=reviewMockTurn(turn);const html=renderCouncilHtml(turn,review,council,runtime,buildPetSnapshots(review,council,runtime),'reduced','nonce');assert.match(html,/Shared Context Graph/);assert.match(html,/3 nodes · 4 relations/);assert.match(html,/motion-reduced/);});
test('renders model effort controls and token usage',()=>{const review=reviewMockTurn(SAMPLE_COUNCIL_TURN);const html=renderCouncilHtml(SAMPLE_COUNCIL_TURN,review,council,{...runtime,tokenUsage:{last:{totalTokens:1200,inputTokens:800,cachedInputTokens:100,outputTokens:300,reasoningOutputTokens:100},modelContextWindow:128000,quotaUsedPercent:42}},buildPetSnapshots(review,council,runtime),'system','nonce');assert.match(html,/codex-model-select/);assert.match(html,/codex-effort-select/);assert.match(html,/codex-model-select-composer/);assert.match(html,/codex-effort-select-composer/);assert.match(html,/1,200 tokens/);assert.match(html,/quota 42%/);});
test('shows Council thinking without fabricated suggestions',()=>{const review={turnId:'demo',roles:['architect','guardian','strategist','notetaker'].map((role)=>({role:role as 'architect'|'guardian'|'strategist'|'notetaker',suggestions:[]}))};const thinking={phase:'reviewing' as const,provider:'codex' as const,message:'Thinking',turnId:'demo'};const html=renderCouncilHtml(SAMPLE_COUNCIL_TURN,review,thinking,runtime,buildPetSnapshots(review,thinking,runtime),'system','nonce');assert.match(html,/The Council is thinking/);assert.match(html,/Reviewing/);});
