import { COUNCIL_ROLES, type CouncilReview, type CouncilRoleDefinition, type CouncilRoleId, type CouncilRoleReview, type CouncilSuggestion, type CouncilTurn } from './domain';
import { hasUsefulCouncilEvidence } from './evidence';
import type { CodexRuntimeStatus } from './runtime/types';

const EMPTY_ROLE_STATUS: Record<CouncilRoleId, string> = { architect: 'Waiting for project context', guardian: 'Nothing to review', strategist: 'Nothing to sequence', notetaker: 'Nothing to preserve' };

export function renderCouncilHtml(turn: CouncilTurn, review: CouncilReview, runtime: CodexRuntimeStatus, nonce: string): string {
  const evidence = hasUsefulCouncilEvidence(turn);
  return document(evidence ? activeView(turn, review, runtime) : emptyView(turn, review, runtime), nonce, evidence ? interactiveScript() : emptyScript());
}

function activeView(turn: CouncilTurn, review: CouncilReview, runtime: CodexRuntimeStatus): string {
  const activeRoles = review.roles.filter((role) => role.suggestions.length > 0).length;
  const suggestions = review.roles.reduce((count, role) => count + role.suggestions.length, 0);
  const real = turn.runtime?.source === 'codex';
  return `<main>
    <div class="header"><div><p class="eyebrow">${real ? 'Completed Codex turn review' : 'Live workspace'}</p><h1>Pets Council</h1></div><button class="action secondary" id="refresh-context">Refresh context</button></div>
    ${runtimeCard(runtime)}${codexConversation(runtime)}
    <section class="panel"><p class="eyebrow">${real ? 'Council review' : 'Deterministic workspace review'}</p><h2>${activeRoles} ${pluralize(activeRoles,'companion')} ${activeRoles===1?'has':'have'} something useful to add.</h2><p>${real ? `The Council reviewed Codex turn ${shortId(turn.turnId)} with the captured project context.` : `${suggestions} suggestions currently come from editor and Git evidence.`}</p>${real ? `<div class="exchange"><p><b>You</b><br>${escapeHtml(turn.userMessage)}</p><p><b>Codex</b><br>${escapeHtml(turn.assistantResponse)}</p></div>` : ''}</section>
    ${contextPills(turn)}${warnings(turn.capture.warnings)}
    <section class="roles">${roles(review,false)}</section>${councilComposer()}
  </main>`;
}

function emptyView(turn: CouncilTurn, review: CouncilReview, runtime: CodexRuntimeStatus): string {
  return `<main><p class="eyebrow">Council waiting</p><section class="panel"><h1>No project context yet</h1><p>Open a folder so the Council can inspect bounded editor and Git evidence.</p><div class="buttons"><button class="action" id="open-folder">Open folder</button><button class="action secondary" id="refresh-context">Refresh context</button></div><small>Captured locally at ${escapeHtml(formatCapturedAt(turn.capture.capturedAt))}.</small></section>${runtimeCard(runtime)}${codexConversation(runtime)}<section class="roles">${roles(review,true)}</section></main>`;
}

function runtimeCard(runtime: CodexRuntimeStatus): string {
  const thread = runtime.thread.thread;
  const details = [`Binary: ${runtime.binary}`,runtime.server?.userAgent,thread?`Thread ${shortId(thread.id)}`:undefined,thread?.model,thread?.modelProvider].filter((v):v is string=>Boolean(v)).join(' · ');
  return `<section class="runtime runtime--${runtime.phase}"><div><p class="eyebrow">Codex runtime</p><h2>${escapeHtml(runtimeTitle(runtime))}</h2><p>${escapeHtml(runtime.message)}</p>${runtime.phase==='ready'?`<p><b>${escapeHtml(runtime.thread.message)}</b></p>`:''}<small>${escapeHtml(details)}</small></div><div class="buttons">${runtimeActions(runtime)}</div></section>`;
}

function runtimeActions(runtime: CodexRuntimeStatus): string {
  if(runtime.phase==='connecting')return '<button class="action" disabled>Connecting…</button>';
  if(runtime.phase!=='ready')return `<button class="action" id="connect-codex">${runtime.phase==='error'?'Retry connection':'Connect Codex'}</button>`;
  const thread=runtime.thread.phase==='starting'?'<button class="action" disabled>Starting session…</button>':`<button class="action" id="start-codex-thread">${runtime.thread.phase==='ready'?'New Codex session':'Start Codex session'}</button>`;
  return `${thread}<button class="action secondary" id="disconnect-codex">Disconnect</button>`;
}

function runtimeTitle(runtime: CodexRuntimeStatus): string { if(runtime.phase==='connecting')return 'Connecting to app-server';if(runtime.phase==='error')return 'Connection failed';if(runtime.phase==='disconnected')return 'Not connected';return runtime.thread.phase==='ready'?'Thread ready':'Handshake complete'; }

function codexConversation(runtime: CodexRuntimeStatus): string {
  if(runtime.phase!=='ready'||runtime.thread.phase!=='ready')return '';
  const running=runtime.turn.phase==='starting'||runtime.turn.phase==='streaming';
  const transcript=runtime.turn.userMessage?`<div class="exchange"><p><b>You</b><br>${escapeHtml(runtime.turn.userMessage)}</p><p><b>Codex</b><br>${escapeHtml(runtime.turn.assistantMessage||(running?'…':'No assistant message returned.'))}</p></div>`:'<p class="muted">The thread is ready. Send the first explicit prompt.</p>';
  return `<section class="panel"><div class="header"><div><p class="eyebrow">Primary assistant</p><h2>Codex conversation</h2></div><span class="phase">${runtime.turn.phase}</span></div>${transcript}<label for="codex-composer">Message Codex</label><textarea id="codex-composer" ${running?'disabled':''} placeholder="Ask Codex about the current project…"></textarea><div class="footer"><small>${escapeHtml(runtime.turn.message)}</small><button class="action" id="send-codex-turn" ${running?'disabled':''}>${running?'Codex is responding…':'Send to Codex'}</button></div><small>Sending starts a real model turn. It never happens automatically.</small></section>`;
}

function contextPills(turn: CouncilTurn): string { const values=[turn.runtime?'Real Codex turn':undefined,turn.workspace.name,turn.workspace.activeFile,turn.workspace.selectedText?`Selection: ${turn.workspace.selectedText.length} chars`:undefined,turn.git?.branch,turn.git?.changedFiles.length?`${turn.git.changedFiles.length} changed files`:undefined,`Captured ${formatCapturedAt(turn.capture.capturedAt)}`].filter((v):v is string=>Boolean(v));return `<div class="pills">${values.map(v=>`<span>${escapeHtml(v)}</span>`).join('')}</div>`; }
function warnings(items: readonly string[]): string { return items.length?`<details><summary>${items.length} context warnings</summary><ul>${items.map(v=>`<li>${escapeHtml(v)}</li>`).join('')}</ul></details>`:''; }
function roles(review: CouncilReview, empty: boolean): string { const defs=new Map(COUNCIL_ROLES.map(r=>[r.id,r]));return review.roles.map(rr=>{const role=defs.get(rr.role);if(!role)throw new Error(`Missing role ${rr.role}`);return empty?emptyRole(rr,role):roleCard(rr,role);}).join(''); }
function roleCard(review: CouncilRoleReview, role: CouncilRoleDefinition): string { const count=review.suggestions.length;const content=count?review.suggestions.map(s=>suggestion(s,role)).join(''):'<p class="muted">This companion found no useful addition.</p>';return roleShell(role,count?`${count} ${pluralize(count,'suggestion')}`:'Nothing to add',content,count===0); }
function emptyRole(review: CouncilRoleReview, role: CouncilRoleDefinition): string { return roleShell(role,EMPTY_ROLE_STATUS[review.role],'<p class="muted">No concrete project signal is available yet.</p>',true); }
function roleShell(role: CouncilRoleDefinition,status:string,content:string,silent:boolean):string{return `<article class="role${silent?' silent':''}"><div class="icon">${role.icon}</div><div><div class="role-head"><h3>${escapeHtml(role.name)}</h3><span>${escapeHtml(status)}</span></div><p class="muted">${escapeHtml(role.purpose)}</p>${content}</div></article>`;}
function suggestion(s:CouncilSuggestion,role:CouncilRoleDefinition):string{return `<article class="suggestion"><h4>${escapeHtml(s.title)}</h4><p>${escapeHtml(s.rationale)}</p><button class="action" data-role="${escapeHtml(role.name)}" data-prompt="${escapeHtml(s.prompt)}">${escapeHtml(s.actionLabel)}</button></article>`;}
function councilComposer():string{return `<section class="panel sticky"><label for="council-composer">Prepared Council prompt</label><textarea id="council-composer" placeholder="Choose a Council suggestion…"></textarea><div class="footer"><small id="composer-status">No suggestion selected.</small><div class="buttons"><button class="action secondary" id="clear-prompt">Clear</button><button class="action" id="copy-prompt">Copy prompt</button></div></div></section>`;}

function document(body:string,nonce:string,script:string):string{return `<!DOCTYPE html><html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta http-equiv="Content-Security-Policy" content="default-src 'none';style-src 'unsafe-inline';script-src 'nonce-${escapeHtml(nonce)}'"><title>Pets Council</title><style>${styles()}</style></head><body>${body}<script nonce="${escapeHtml(nonce)}">${script}</script></body></html>`;}
function styles():string{return `:root{color-scheme:light dark;font-family:var(--vscode-font-family)}*{box-sizing:border-box}body{margin:0;padding:24px;color:var(--vscode-foreground);background:var(--vscode-editor-background)}main{width:min(960px,100%);margin:auto}h1,h2,h3,h4,p{margin-top:0}.header,.footer,.runtime,.role-head{display:flex;justify-content:space-between;align-items:flex-start;gap:16px}.eyebrow{margin:0 0 6px;color:var(--vscode-descriptionForeground);font-size:11px;font-weight:700;letter-spacing:.1em;text-transform:uppercase}.action{padding:7px 11px;border:1px solid transparent;border-radius:6px;color:var(--vscode-button-foreground);background:var(--vscode-button-background);cursor:pointer}.secondary{color:var(--vscode-foreground);background:transparent;border-color:var(--vscode-panel-border)}button:disabled{opacity:.6}.buttons{display:flex;gap:8px;flex-wrap:wrap}.panel,.runtime{margin:16px 0;padding:18px;border:1px solid var(--vscode-panel-border);border-radius:14px;background:var(--vscode-sideBar-background)}.runtime--ready{border-color:var(--vscode-testing-iconPassed,var(--vscode-focusBorder))}.runtime--error{border-color:var(--vscode-inputValidation-errorBorder,var(--vscode-errorForeground))}small,.muted{color:var(--vscode-descriptionForeground);line-height:1.45}.phase,.role-head span{font-size:11px;text-transform:uppercase;color:var(--vscode-descriptionForeground)}.exchange{display:grid;gap:9px;margin:12px 0}.exchange p{padding:11px;border:1px solid var(--vscode-panel-border);border-radius:9px;white-space:pre-wrap;background:var(--vscode-editor-background)}textarea{width:100%;min-height:92px;margin-top:8px;padding:11px;border:1px solid var(--vscode-panel-border);border-radius:8px;color:var(--vscode-input-foreground);background:var(--vscode-input-background);font:inherit}.footer{align-items:center;margin-top:10px}.pills{display:flex;gap:8px;flex-wrap:wrap;margin:16px 0}.pills span{padding:5px 9px;border:1px solid var(--vscode-panel-border);border-radius:999px;font-size:11px;color:var(--vscode-descriptionForeground)}.roles{display:grid;gap:12px}.role{display:grid;grid-template-columns:auto 1fr;gap:14px;padding:16px;border:1px solid var(--vscode-panel-border);border-radius:13px;background:var(--vscode-sideBar-background)}.silent{opacity:.72}.icon{font-size:24px}.suggestion{margin-top:9px;padding:12px;border:1px solid var(--vscode-panel-border);border-radius:9px;background:var(--vscode-editor-background)}.sticky{position:sticky;bottom:12px}@media(max-width:640px){body{padding:14px}.header,.footer,.runtime{display:block}.buttons{margin-top:10px}.role{grid-template-columns:1fr}}`;}
function runtimeScript():string{return `for(const [id,type] of [['connect-codex','connectCodex'],['disconnect-codex','disconnectCodex'],['start-codex-thread','startCodexThread']]){document.getElementById(id)?.addEventListener('click',()=>vscode.postMessage({type}));}const send=document.getElementById('send-codex-turn'),input=document.getElementById('codex-composer');if(send&&input){const submit=()=>{const value=input.value.trim();if(value){send.disabled=true;vscode.postMessage({type:'startCodexTurn',value});}};send.addEventListener('click',submit);input.addEventListener('keydown',e=>{if((e.metaKey||e.ctrlKey)&&e.key==='Enter'){e.preventDefault();submit();}});}`;}
function interactiveScript():string{return `const vscode=acquireVsCodeApi();${runtimeScript()}const c=document.getElementById('council-composer'),s=document.getElementById('composer-status'),state=vscode.getState();if(state?.draft)c.value=state.draft;document.querySelectorAll('[data-prompt]').forEach(b=>b.addEventListener('click',()=>{c.value=b.dataset.prompt||'';vscode.setState({draft:c.value});s.textContent='Prepared from '+(b.dataset.role||'Council')+'.';}));c.addEventListener('input',()=>vscode.setState({draft:c.value}));document.getElementById('copy-prompt').addEventListener('click',()=>{const value=c.value.trim();if(value)vscode.postMessage({type:'copyPrompt',value});});document.getElementById('clear-prompt').addEventListener('click',()=>{c.value='';vscode.setState({draft:''});});document.getElementById('refresh-context').addEventListener('click',()=>vscode.postMessage({type:'refreshContext'}));`;}
function emptyScript():string{return `const vscode=acquireVsCodeApi();${runtimeScript()}document.getElementById('open-folder')?.addEventListener('click',()=>vscode.postMessage({type:'openFolder'}));document.getElementById('refresh-context')?.addEventListener('click',()=>vscode.postMessage({type:'refreshContext'}));`;}
export function formatCapturedAt(value:string):string{const d=new Date(value);return Number.isNaN(d.getTime())?value:new Intl.DateTimeFormat(undefined,{hour:'2-digit',minute:'2-digit',second:'2-digit'}).format(d);}
function shortId(value:string):string{return value.length<=12?value:`${value.slice(0,8)}…${value.slice(-4)}`;}
function pluralize(n:number,s:string):string{return n===1?s:`${s}s`;}
function escapeHtml(v:string):string{return v.replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#039;');}
